Repository Kernel-GL-HRK/gl-kernel-training-2018, pull requests merged in 2018-11, with the labels that each got.

#60 04-KernelModule: Add finished homework task
  04-KernelModule/Makefile
  04-KernelModule/README.md
  04-KernelModule/log.txt
  04-KernelModule/mymodule.c
Labels: OK

#57 Lesson_04: Add simple kernel module, Makefile and out.txt
  04-KernelModule/Makefile
  04-KernelModule/module_1.c
  04-KernelModule/out.txt
Labels: OK

#62 Homework04
  04-KernelModule/simple_kernel_module/Makefile
  04-KernelModule/simple_kernel_module/simple_kernel_module.c
  04-KernelModule/simple_kernel_module/simple_kernel_module_log_fail
  04-KernelModule/simple_kernel_module/simple_kernel_module_log_success
Labels: OK

#73 Lesson 05
  05-Interfaces/module_procfs/Makefile
  05-Interfaces/module_procfs/to_upper_case.c
  05-Interfaces/module_sysfs/Makefile
  05-Interfaces/module_sysfs/to_lower_case.c
Labels: OK

#74 03 make - added finished task
  03-make/make_simplest/Makefile
  03-make/make_soup/Makefile
Labels: ready

#64 03-bash: finished task
  03-bash/task1.sh
  03-bash/task2.sh
Labels: ready

#66 Lesson03 bash: Eugene.Ovdiyuk
  03-Bash/task1.sh
  03-bash/README.md
  03-bash/task1.sh
Labels: ready

#67 Lesson03 make: Eugene.Ovdiyuk
  03-make/README.md
  03-make/make_email/Makefile
  03-make/make_homework/Makefile
  03-make/make_homework/Makefile_output.log
  03-make/make_homework/README.md
  03-make/make_homework/magazin/ovoshchi.txt
  03-make/make_homework/pechka/gaz.txt
  03-make/make_homework/pechka/pechka.txt
  03-make/make_homework/stol/kasha.txt
  03-make/make_homework/stol/kastrulya.txt
  03-make/make_simplest/Makefile
  03-make/make_simplest/main.c
Labels: ready

#68 04-KernelModule: Add source file, makefile and log file
  03-bash/.#task1.sh
  04-KernelModule/.cache.mk
  04-KernelModule/Makefile
  04-KernelModule/README.md
  04-KernelModule/glModule.c
  04-KernelModule/logs.txt
Labels: changes requested

#61 lesson04: Implement simple module
  04-KernelModule/Makefile
  04-KernelModule/hello_printk.c
  04-KernelModule/log.sh
  04-KernelModule/log.txt
Labels: OK

#76 Lesson05: sysfs and procfs task completed
  05-Interfaces/solution/Makefile
  05-Interfaces/solution/convert_module.c
  05-Interfaces/solution/test_uppercase.py
Labels: OK

#83 Lesson02: Ivan Parfyonov
  02-Git/Makefile
  02-Git/main.c
Labels: OK

#77 Lesson 06
  06-TimeManagement/Makefile
  06-TimeManagement/timer.c
Labels: OK

#89 Lesson 06: added sysfs kernel module with TimeManagement HW
  06-TimeManagement/06_timeMan/Makefile
  06-TimeManagement/06_timeMan/readme.txt
  06-TimeManagement/06_timeMan/timeMan.c
Labels: OK

#93 06-Time management: add kernel module with time management
  06-TimeManagement/Makefile
  06-TimeManagement/time_management.c
Labels: OK

#98 06-TimeManagement: implement homework with system timer, timer, absol…
  06-TimeManagement/Makefile
  06-TimeManagement/itime.c
Labels: OK
