Repository Kernel-GL-HRK/gl-kernel-training-2018, pull requests merged in 2018-10, with the labels that each got.

#1 02-Git: Add homework
  02-Git/README.md
Labels: ready, reviewed

#18 Homework02
  homework/lesson02/main.cpp
  homework/lesson02/makefile
Labels: ready, reviewed

#20 02 git solution
  02-Git/test.txt
Labels: ready, reviewed

#21 Lesson 2 homework
  02-Git/game.c
  02-Git/makefile
Labels: ready, reviewed

#26 02-Git: Task solution
  02-Git/main.c
Labels: ready, reviewed

#27 99-task: Add simple program
  99-test/main.c
Labels: RFC (example), ready, reviewed

#31 02-Git homework
  02-Git/Makefile
  02-Git/homework.c
Labels: ready, reviewed

#28 Lesson02
  02-Git/makefile
  02-Git/rps.c
Labels: ready

#23 xvikili_lesson02
  02-Git/Makefile
  02-Git/src/main.c
Labels: ready, reviewed

#33 02-Git: Add finished task
  02-Git/Makefile
  02-Git/README.md
  02-Git/main.c
Labels: ready, reviewed

#10 Lesson02
  02-Git/solution/Makefile
  02-Git/solution/game.c
Labels: ready, reviewed

#29 02 git task
  02-Git/main.c
  02-Git/makefile
Labels: ready, reviewed

#11 Lesson 02
  02-Git/Makefile
  02-Git/main.c
Labels: changes requested, ready, reviewed

#34 Lesson02: Eugene.ovdiyuk
  02-Git/Makefile
  02-Git/game.c
Labels: ready, reviewed

#48 Lesson03: GNU Make tasks done
  03-make/make_simplest/Makefile
  03-make/make_soup/Makefile
  03-make/make_soup/chop.sh
  03-make/make_soup/deploy_dirs.sh
  03-make/make_soup/food-market/carrot
  03-make/make_soup/food-market/meat
  03-make/make_soup/food-market/onion
  03-make/make_soup/food-market/potato
  03-make/make_soup/kitchen/gas_cooker
  03-make/make_soup/kitchen/table/knife
  03-make/make_soup/kitchen/table/pot
  03-make/make_soup/move_resource.sh
  03-make/set_example.mk
Labels: ready

#47 Lesson 03 make
  03-make/make_simplest/Makefile
  03-make/soup_task/Makefile
  03-make/soup_task/food-market/porridge
  03-make/soup_task/food-market/potato
  03-make/soup_task/food-market/water
  03-make/soup_task/kitchen/table/spoon
Labels: ready

#50 Lesson 04
  04-KernelModule/Error.log
  04-KernelModule/Makefile
  04-KernelModule/Ok.log
  04-KernelModule/testmodule.c
Labels: OK

#49 Lesson_03: Add project for making basic soup
  03-make/make_soup/food-market/carrot.txt
  03-make/make_soup/food-market/potato.txt
  03-make/make_soup/food-market/salt.txt
  03-make/make_soup/food-market/water.txt
  03-make/make_soup/makefile
Labels: ready

#42 Lesson 03: Initial solution for task on shell scripting
  03-bash/task1.sh
Labels: ready

#52 Lesson_04: Add simple kernel module sourcefile, makefile and log
  04-KernelModule/Makefile
  04-KernelModule/log.txt
  04-KernelModule/simpleModule.c
Labels: OK

#35 Lesson2(Git) - Task finished
  02-Git/Makefile
  02-Git/README.md
  02-Git/main.c
Labels: changes requested

#55 Lesson04: Simple kernel module and logs from manipulations with it
  04-KernelModule/solution/Makefile
  04-KernelModule/solution/result.txt
  04-KernelModule/solution/solution.c
Labels: OK

#46 Lesson_03: Add bash scrit with partial functionality from homework task
  03-bash/task1.sh
Labels: ready

#40 03-Bash homework
  03-bash/task1.sh
  03-bash/task2.sh
Labels: ready

#41 Lesson 03/bash: Add a script with a basic logic
  03-bash/task1.sh
  03-bash/task2.sh
Labels: ready

#43 Lesson03
  03-bash/README.md
  03-bash/README1.md
  03-bash/addsyspath.sh
  03-bash/task1.out
  03-bash/task1.sh
  03-bash/task2.sh
  03-make/README.md
  03-make/cook-it/Makefile
  03-make/cook-it/boil
  03-make/cook-it/fried_onion
  03-make/cook-it/fry
  03-make/cook-it/fry_onion
  03-make/cook-it/fry_onion.sh
  03-make/cook-it/meat
  03-make/cook-it/oil
  03-make/cook-it/onion
  03-make/cook-it/pilaf
  03-make/cook-it/pilaf.sh
  03-make/cook-it/rice
  03-make/cook-it/sause
  03-make/cook-it/soup
  03-make/cook-it/soup.sh
  03-make/cook-it/spices
  03-make/cook-it/tea
  03-make/cook-it/walnuts
  03-make/cook-it/water
  03-make/make_email/Makefile
  03-make/make_simplest/Makefile
  03-make/make_simplest/main.c
  03-make/read
Labels: ready

#56 Lesson 3: Bash, Task1 - Add bash script with partially implemented functionality
  03-bash/task1.sh
  04-KernelModule/README.md
Labels: ready

#14 Lesson02
  02-Git/Makefile
  02-Git/main.c
Labels: OK
